services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    restart: always
    volumes:
      - "./docker/.mysql-data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      environment_network:
        ipv4_address: 172.29.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    networks:
      environment_network:
        ipv4_address: 172.29.0.3

  frankenphp:
    build:
      context: ./docker/frankenphp
      dockerfile: Dockerfile
    container_name: frankenphp
    restart: always
    volumes:
      - ./:/app
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    networks:
      environment_network:
        ipv4_address: 172.29.0.4


  node:
    image: node:20
    container_name: node
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      environment_network:
        ipv4_address: 172.29.0.5

networks:
  environment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
